"""The least-defended surface in a lesson is the sentence that cites nothing.

Eight gates check structure, citation presence, tag balance and mission-strip
fidelity. None checks whether a sentence is true, and an uncited explanatory
sentence — the one doing the actual teaching — has no denominator to be checked
against. Across two CodeRabbit rounds the largest defect category was exactly
that: the unhedged universal quantifier in uncited prose, four of them false at
a boundary the author had not pictured.

`scripts/prose_universals.py` is ADVISORY: exit 0 whatever it finds, absent
from `unit-gates.json`, absent from CI. These tests hold it to being a useful
reading order rather than a gate — it must surface all four known-false
sentences, and it must not be quietly turned into something blocking.
"""
import subprocess
import sys
from pathlib import Path

import pytest

from scripts.prose_universals import flags, main, selftest, sentences

ROOT = Path(__file__).resolve().parents[1]

# The four sentences confirmed false in review, with the boundary each breaks
# at. This is the negative-control corpus the observation asked for; it is
# stored here because every one of them has since been corrected in the
# lessons, so the live corpus cannot supply them.
KNOWN_FALSE = [
    ("The singular chain group is uncountable for any space with more than"
     " one point.",
     "a discrete space on m points has exactly m singular n-simplices, since"
     " the standard n-simplex is connected"),
    ("There is no constraint on a space visible in the mere isomorphism type"
     " of its fundamental group.",
     "Hatcher's Corollary 1.28 constrains the class of 2-complexes"),
    ("The centre of the torus-knot group is always the infinite cyclic"
     " subgroup generated by that element.",
     "false at m = 1 or n = 1; the source states m, n > 1 on the cited page"),
    ("Z/2 torsion is never visible to a barcode computed over F_2.",
     "H_*(RP^2; F_2) = (F_2, F_2, F_2); only torsion-ness is lost"),
]


@pytest.mark.parametrize("sentence,why_false",
                         KNOWN_FALSE,
                         ids=["chain-group", "fundamental-group",
                              "torus-knot", "f2-torsion"])
def test_every_known_false_universal_is_surfaced(sentence, why_false):
    assert flags("<p>%s</p>" % sentence), why_false


def test_the_self_referential_one_is_the_strongest_control():
    """The fourth was written as a CORRECTION to a finding in the previous
    round, and asserted a false universal of its own. Rescoping a claim is not
    a licence to assert: a correction inherits exactly the lack of defence that
    produced the error it replaces."""
    correction = KNOWN_FALSE[3][0]
    assert flags("<p>%s</p>" % correction)


def test_a_hedged_universal_is_not_flagged():
    """"usually uncountable" appears in the corpus and is right. An advisory
    that fires on correct prose is an advisory nobody reads."""
    assert flags("<p>The singular chain group is usually uncountable.</p>") == []


def test_a_cited_sentence_is_not_this_tools_population():
    """Gate 2 has a denominator for it."""
    assert flags("<p>By Theorem 1.28 no 2-complex has that group.</p>") == []
    assert flags("<p>Munkres never assumes Hausdorff, p. 43.</p>") == []


def test_there_is_no_boundary_filter_and_that_is_deliberate():
    """The rule that would suppress a sentence naming "more than one point" or
    "infinite" suppressed two of the four known-false controls. Naming a
    degenerate word is not evidence the author checked the degenerate case.
    This pins the decision so a later "reduce the noise" pass has to break a
    test rather than quietly reintroduce it."""
    import scripts.prose_universals as mod
    assert not hasattr(mod, "BOUNDARY")
    # The cost of not having it, stated: a correct hypothesis-stating sentence
    # is flagged too.
    assert flags("<p>For nontrivial m and n the centre is always infinite"
                 " cyclic.</p>")


def test_script_contents_are_not_prose():
    assert flags("<script>var s = 'every point is fixed.';</script>") == []


def test_sentences_are_not_split_at_a_page_abbreviation():
    """Shared with citations.py rather than reimplemented (G5)."""
    assert len(sentences("Read p. 43. Then continue.")) == 2


def test_quantifiers_are_reported_deduplicated_and_sorted():
    assert flags("<p>No space is never both, and no map is.</p>")[0][1] == [
        "never", "no"]


# --- it must stay advisory -------------------------------------------------

def test_a_run_over_a_flagged_lesson_still_exits_zero():
    """The load-bearing property. A blocking gate at this precision would
    train the author to phrase around it, which is worse than nothing: the
    sentence stops matching and stays false."""
    lesson = ROOT / "lessons" / "at1" / "at1-07.html"
    assert flags(lesson.read_text(encoding="utf-8")), "expected a flagged file"
    assert main([str(lesson)]) == 0


def test_it_is_absent_from_the_gate_manifest():
    import json
    manifest = json.loads((ROOT / "curriculum" / "unit-gates.json").read_text(
        encoding="utf-8"))
    argv = " ".join(part for gate in manifest["gates"] for part in gate["argv"])
    assert "prose_universals" not in argv


def test_it_is_absent_from_ci():
    workflow = (ROOT / ".github" / "workflows" / "quality-gates.yml").read_text(
        encoding="utf-8")
    assert "prose_universals" not in workflow


def test_the_authoring_guide_points_at_it():
    """An advisory nobody is told to run is an advisory nobody runs."""
    guide = (ROOT / "curriculum" / "LESSON-GUIDE.md").read_text(encoding="utf-8")
    assert "prose_universals.py" in guide


def test_the_selftest_passes():
    assert selftest() == 0


def test_usage_error_is_exit_2_not_0():
    """Exit 0 means "advisory ran"; it must not also mean "you called it
    wrong"."""
    assert main([]) == 2


def test_the_script_runs_standalone():
    result = subprocess.run([sys.executable, "scripts/prose_universals.py",
                             "--selftest"], cwd=ROOT, capture_output=True,
                            text=True, encoding="utf-8", errors="replace")
    assert result.returncode == 0
    assert "checks passed" in result.stdout


# --- Codex review of PR #32 -------------------------------------------------

def test_a_hedge_in_the_next_block_does_not_excuse_this_one():
    """Collapsing all whitespace merged adjacent paragraphs into one sentence,
    so the second paragraph's "Usually" suppressed the first one's false
    universal."""
    got = flags("<p>No map exists</p><p>Usually this construction works.</p>")
    assert [s for s, _w in got] == ["No map exists"]


def test_a_citation_in_the_next_block_does_not_excuse_this_one():
    got = flags("<p>No map exists</p><p>See Theorem 1.2.</p>")
    assert [s for s, _w in got] == ["No map exists"]


def test_whitespace_inside_a_block_is_still_normalised():
    got = flags("<p>There   is\n   no such map.</p>")
    assert [s for s, _w in got] == ["There is no such map."]
